apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  labels:
    app: alertmanager
data:
  config.yml: |-
    route:
      receiver: 'scdf'

    receivers:
      - name: 'scdf'
        webhook_configs:
          - url: http://alertwebhook:8085/alert
