[[spring-cloud-data-flow-samples-overview]]

This repository provides sample starter applications and code for use with the Spring Cloud Data Flow project. The following samples are available:

== Streaming

include::streaming/cassandra/overview.adoc[]

include::streaming/jdbc/overview.adoc[]

include::streaming/gemfire/overview.adoc[]

== Task / Batch

include::tasks/overview.adoc[]

////
A simple Spring Batch job running as short-lived task in Cloud Foundry.

=== Functions

==== link:functions/README.adoc[functions-in-scdf]

A simple demonstration of Spring Cloud Function and Spring Cloud Data Flow integration.

=== Analytics

==== link:analytics/twitter-analytics/README.adoc[twitter-analytics]

A data pipeline demonstration that consumes data from twitter-firehose using `twitterstream` source application and computes simple analytics over data-in-transit with the help of `field-value-counter` sink application.

=== Data Science

==== link:datascience/species-prediction/README.adoc[species-prediction]

A simple demonstration to walkthrough the steps to compute real-time predictions using https://en.wikipedia.org/wiki/Predictive_Model_Markup_Language[PMML] application.
////
