{
 "title": "scdf-influxdb-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stream",
    "label": "Stream",
    "query": "show tag values with key=\"stream_name\""
   },
   {
    "name": "application",
    "label": "application",
    "query": "show tag values with key=\"application_name\" WHERE stream_name='$stream'"
   },
   {
    "name": "application_id",
    "label": "ApplicationId",
    "query": "show tag values from \"spring_integration_send\" with key = \"application_guid\" WHERE stream_name = '$stream'"
   }
  ]
 },
 "panels": [
  { "title": "Input Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "input" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Channel Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "input" }
     ]
    }
   ]
  },
  { "title": "Output Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Output Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"count\" FROM \"spring_integration_send\" WHERE (\"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"name\" = 'output') AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "output" },
      { "condition": "AND", "key": "stream_name", "operator": "=~", "value": "/^$stream$/" }
     ]
    }
   ]
  },
  {
   "title": "Output Channel Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "query": "SELECT \"mean\" FROM \"spring_integration_send\" WHERE (\"stream_name\" =~ /^$stream$/ AND \"application_name\" =~ /^$application$/ AND \"type\" = 'channel' AND \"name\" = 'output') AND $timeFilter GROUP BY \"stream_name\", \"application_name\", \"result\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "output" }
     ]
    }
   ]
  },
  { "title": "Error Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Error Channel Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
     ]
    }
   ]
  },
  {
   "title": "Error Channel Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "channel" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "errorChannel" }
     ]
    }
   ]
  },
  { "title": "Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Handlers Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  {
   "title": "Handlers Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "spring_integration_send",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "handler" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!=",
       "value": "org_springframework_cloud_stream_app_log_sink_LogSinkConfiguration_logSinkHandler_serviceActivator_handler"
      }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ]
    },
    {
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "stream_name" ], "type": "tag" },
      { "params": [ "application_name" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stream_name", "operator": "=~", "value": "/^$stream$/" },
      { "condition": "AND", "key": "application_name", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  }
 ]
}