{
 "title": "SCDF Analytics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top 10 Lang",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(language_total) by (lang)))"
    }
   ]
  },
  {
   "title": "Hastags",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 22, "w": 9, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(topk(100, sum(hashtags_total) by (hastag)))"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "digrich-bubblechart-panel",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(language_total) by (lang)" }
   ]
  }
 ]
}