[[spring-cloud-data-flow-samples-sftp-file-ingest-overview]]
:sectnums:
:docs_dir: ../..
=== Batch File Ingest - SFTP Demo

In the <<Batch File Ingest>> sample we built a link:https://projects.spring.io/spring-batch[Spring Batch] application that link:https://cloud.spring.io/spring-cloud-dataflow[Spring Cloud Data Flow] launched as a task to process a file.
This time we will build on that sample to create and deploy a link:https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-streams[stream] that launches that task.
The stream will poll an SFTP server and, for each new file that it finds, will download the file and launch the batch job to process it.

The source for the demo project is located in the `batch/file-ingest` directory at the top-level of this repository.

==== Prerequisites
* A Running Data Flow Shell
include::{docs_dir}/shell.adoc[]

include::local.adoc[]

include::pcf.adoc[]

==== Summary

In this sample, you have learned:

* How to process SFTP files with a batch job
* How to create a stream to poll files on an SFTP server and launch a batch job
* How to verify job status via logs and shell commands
* How the Data Flow Task Launcher limits concurrent task executions
* How to avoid processing duplicate files
