apiVersion: v1
kind: Service
metadata:
  name: alertwebhook
  labels:
    app: alertwebhook
spec:
  # If you are running k8s on a local dev box, using minikube, or Kubernetes on docker desktop you can use type NodePort instead
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: alertwebhook
