{
 "title": "SCDF Analytics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 10 Lang",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(language_total) by (lang)))",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Hastags",
   "type": "piechart",
   "gridPos": { "h": 22, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(50, sum(hashtags_total) by (htag)))",
     "legendFormat": "{{htag}}"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(language_total) by (lang)", "legendFormat": "{{lang}}" }
   ]
  }
 ]
}