#!/bin/bash
version=2.5.1.RELEASE
cd "$(dirname "$0")"

rm -fr spring-cloud-dataflow-server*.jar
wget https://repo.spring.io/libs-release-local/org/springframework/cloud/spring-cloud-dataflow-server/$version/spring-cloud-dataflow-server-$version.jar

pushd ..
./gradlew clean build
./mvnw clean package
popd

echo "Diff gradle build"
diff <(unzip -l spring-cloud-dataflow-server-$version.jar|grep BOOT-INF/lib|awk '{print $4}'|sort) <(unzip -l ../build/libs/custom-dataflow-server-gradle-2.0.0-SNAPSHOT.jar|grep BOOT-INF/lib|awk '{print $4}'|sort)

echo "Diff maven build"
diff <(unzip -l spring-cloud-dataflow-server-$version.jar|grep BOOT-INF/lib|awk '{print $4}'|sort) <(unzip -l ../target/custom-dataflow-server-maven-2.0.0-SNAPSHOT.jar|grep BOOT-INF/lib|awk '{print $4}'|sort)
