#!/bin/bash
version=2.5.0.RELEASE
cd "$(dirname "$0")"

echo "Diff gradle build"
diff <(unzip -l spring-cloud-dataflow-server-$version.jar|grep BOOT-INF/lib|awk '{print $4}'|sort) <(unzip -l ../build/libs/custom-dataflow-server-gradle-2.0.0-SNAPSHOT.jar|grep BOOT-INF/lib|awk '{print $4}'|sort)

echo "Diff maven build"
diff <(unzip -l spring-cloud-dataflow-server-$version.jar|grep BOOT-INF/lib|awk '{print $4}'|sort) <(unzip -l ../target/custom-dataflow-server-maven-2.0.0-SNAPSHOT.jar|grep BOOT-INF/lib|awk '{print $4}'|sort)
