= Cloud Scheduler Migration

The purpose of this project is to migrate existing schedules created with Spring
Cloud Data Flow 2.2.0 and before to the new 2.3.0 format and stage the
SchedulerTaskLauncher.  This is a Spring Boot application that utilizes Spring Batch to create a workflow
to migrate the schedules.  This is a Single Step Spring Batch Job that does the following:

* Read - Retrieves all schedules from scheduler.

* Process - Enriches the Schedule request with App and Deployer properties from the scheduler (or deployed app)
as well as data from the TaskDefinition.

* Write - Deploys artifacts if required and creates the new schedule.  Once the migrated
schedule has been created, the old schedule is destroyed.

In the case that the application fails with an exception.  You can re-execute the
application and it will pick up where it left off.   Thanks Spring Batch! :-)

== Build the project

```
mvn clean install
```

== Running The Project For Cloud Foundry

=== Launching your migration
1) Create a manifest.yml file in a work directory.
```
---
applications:
- name: schedulemigrator
  host: schedulemigrator
  memory: 1G
  disk_quota: 1G
  instances: 0
  path: <location of the jar>
  env:
    SPRING_APPLICATION_NAME: schedulemigrator
    spring_cloud_deployer_cloudfoundry_url: <CF API URL>
    spring_cloud_deployer_cloudfoundry_org: <Your org>
    spring_cloud_deployer_cloudfoundry_space: <your space>
    spring_cloud_deployer_cloudfoundry_username: <Your CF user name>
    spring_cloud_deployer_cloudfoundry_password: <Your CF password>
    spring_cloud_deployer_cloudfoundry_skipSslValidation: <true/false>
    spring_cloud_deployer_cloudfoundry_services: <your SCDF database service,your scheduler service>
    spring_cloud_scheduler_cloudfoundry_schedulerUrl: <URL to scheduler service>
    spring_profiles_active: cf
    spring.cloud.deployer.cloudfoundry.healthCheckTimeout: 300
    spring.cloud.deployer.cloudfoundry.apiTimeout: 300
    dataflowServerUri: <Your SCDF server URI>
    spring_cloud_task_closecontextEnabled: true
    remoteRepositories_repo1_url: https://repo.spring.io/libs-snapshot
services:
- <Your SCDF database service>
- <Your SCDF scheduler service>
```
2) From the command line use the cf cli to log into your org and space for which you will migrate your schedules
```
cf login -a <your CF API endpoint>
```
-or if you need to skip ssl validation-
```
cf login -a <your CF API endpoint> --skip-ssl-validation
```


3) Now push the schedulemigrator from the directory where the manifest.yml is present:
```
cf push
```

3) Now launch the schedulemigrator using the command below:
```
cf rt schedulemigrator "JAVA_OPTS=\"-agentpath:\$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=\$TMPDIR -XX:ActiveProcessorCount=\$(nproc) -Djava.ext.dirs=\$PWD/.java-buildpack/container_security_provider:\$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=\$PWD/.java-buildpack/java_security/java.security \$JAVA_OPTS\" && CALCULATED_MEMORY=\$(\$PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=\$MEMORY_LIMIT -loadedClasses=26092 -poolType=metaspace -stackThreads=250 -vmOptions=\"\$JAVA_OPTS\") && echo JVM Memory Configuration: \$CALCULATED_MEMORY && JAVA_OPTS=\"\$JAVA_OPTS \$CALCULATED_MEMORY\" && MALLOC_ARENA_MAX=2 SERVER_PORT=\$PORT eval exec \$PWD/.java-buildpack/open_jdk_jre/bin/java \$JAVA_OPTS -cp \$PWD/. org.springframework.boot.loader.JarLauncher"
```

=== Configuring Your Deployer Properties
When migrating deployer properties there are some properties that can be obtained
from the deployed droplets or the schedule to be migrated.  Others can not
be obtained from the system and must be set as a property that will affect all
schedules to be migrated.  If a property is in MigrateProperties is not set then
the default will be used.


==== Obtained from Schedule or droplet
* buildpack
* memory
* disk
* healthcheck
* healthCheckHttpEndpoint
* useSpringApplicationJson
* services
* domain
* routes
* host

==== Deployer properties to be applied to all migrated schedules:
* healthCheckTimeout
* apiTimeout
* statusTimeout
* stagingTimeout
* startupTimeout
* maximumConcurrentTasks
* javaOpts

NOTE: Descriptions of these properties can be found : https://github.com/cppwfs/spring-cloud-dataflow-samples/blob/SCDF-121/dataflow-migrate-schedules/src/main/java/io/spring/migrateschedule/service/MigrateProperties.java[here]

==== Properties Not Migrated:
* instances
* enableRandomAppNamePrefix
* appNamePrefix
* deleteRoutes
* pushTaskAppsEnabled




== Running The Project For Kubernetes
TBD