name: CI PRs

on:
  pull_request:

jobs:
  build:
    name: Call Build Workflow
    uses: spring-cloud/spring-cloud-dataflow-samples/.github/workflows/ci.yml@main
    with:
      maven-build-only: true
    secrets:
      JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
