name: CI Publish

on:
  workflow_call:
    secrets:
      jfArtifactorySpring:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    name: CI Publish
    steps:
    - uses: actions/checkout@v2
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.8.4
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.46.4
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.jfArtifactorySpring }}
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-resolve=repo.spring.io \
          --server-id-deploy=repo.spring.io \
          --repo-resolve-releases=libs-milestone \
          --repo-resolve-snapshots=libs-snapshot \
          --repo-deploy-releases=release \
          --repo-deploy-snapshots=snapshot
        echo JFROG_CLI_BUILD_NAME=spring-shell-main >> $GITHUB_ENV
        echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV
    - name: Build and Publish
      run: |
        jfrog rt mvn -B clean install -DskipTests
        jfrog rt build-publish
