name: CI PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI PR Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          cache: maven
      - name: Build kafka-samples
        run: ./mvnw -B package
        working-directory: kafka-samples
      - name: Build multio-samples/ticktock
        run: ./mvnw -B package
        working-directory: multio-samples/ticktock
