name: CI-TASK-3

on:
  # Called by UI
  workflow_dispatch:

  # Called when code gets pushed to the main branch
  push:
    branches:
      - main
    paths:
      - 'timestamp-task-3'
      - 'timestamp-batch-3'

  # Called by the CI PR workflow (invokes main CI but skips publish and push)
  workflow_call:
    inputs:
      maven-build-only:
        type: boolean
        description: Skip Artifactory publish and Docker push for all apps
        required: false
        default: false
    secrets:
      JF_ARTIFACTORY_SPRING:
        description: 'encoded JFrog server id configuration'
        required: false
      DOCKER_USERNAME:
        description: 'docker username'
        required: false
      DOCKER_TOKEN:
        description: 'docker password'
        required: false

jobs:

  timestamp-task-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the build version
        id: buildversion
        run: |
          cd timestamp-task-3
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "BUILD_VERSION=$VERSION"
          cd ..
      - uses: ./.github/actions/build-sample-app
        with:
          app-dir: 'timestamp-task-3'
          mvn-build-commands: '-B clean install spring-boot:build-image'
          artifactory-publish: ${{ inputs.maven-build-only != true }}
          jf-server-id: ${{ vars.JF_SERVER_ID }}
          jf-artifactory-spring: ${{ secrets.JF_ARTIFACTORY_SPRING }}
          artifactory-repo-deploy-releases: 'libs-milestone-local'
          docker-push: ${{ inputs.maven-build-only != true }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
          java-version: '17'
          docker-images: springcloudtask/timestamp-task:${{steps.buildversion.outputs.BUILD_VERSION}}

  timestamp-batch-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the build version
        id: buildversion
        run: |
          cd timestamp-batch-3
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "BUILD_VERSION=$VERSION"
          cd ..
      - uses: ./.github/actions/build-sample-app
        with:
          app-dir: 'timestamp-batch-3'
          mvn-build-commands: '-B clean install spring-boot:build-image'
          artifactory-publish: ${{ inputs.maven-build-only != true }}
          jf-server-id: ${{ vars.JF_SERVER_ID }}
          jf-artifactory-spring: ${{ secrets.JF_ARTIFACTORY_SPRING }}
          artifactory-repo-deploy-releases: 'libs-milestone-local'
          docker-push: ${{ inputs.maven-build-only != true }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
          java-version: '17'
          docker-images: springcloudtask/timestamp-batch-task:${{steps.buildversion.outputs.BUILD_VERSION}}

  completed:
    runs-on: ubuntu-latest
    needs:
      - timestamp-task-3
      - timestamp-batch-3
    steps:
      - name: 'Completed'
        shell: bash
        run: echo "::info ::completed"
